server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/


spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/user/**
      - id: department-service
        uri: lb://department-service
        predicates:
        - Path=/department/**





management:
  endpoints:
    web:
      exposure:
        include: "*"

